### ISSUE TITLE
esphome api crashes when obis_do component is added

### ISSUE THREAD

**Issue by jonathanarchergithub** [mampfes/esphome_obis_d0#23]
I setup esphome on my WS-IR-WIFI (esp01-m). I can connect to the api as long as the obis_d0 component is not included in the config. As soon as I enable it I get the following api error:

INFO Successfully resolved ws-ir-obis @ 192.168.0.101 in 0.000s
WARNING Can't connect to ESPHome API for ws-ir-obis @ 192.168.0.101: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.0.101', port=6053))]: [Errno 111] Connect call failed ('192.168.0.101', 6053) (SocketAPIError)

Anything I could have done wong? Current config:

```
esphome:
  name: ws-ir-obis
  friendly_name: "WS-IR OBIS Zähler"

external_components:
  - source:
      type: git
      url: https://github.com/mampfes/esphome_obis_d0
      ref: main
  
esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Stromzaehler"
    password: "Stromzaehler"

captive_portal:

api:
  port: 6053

logger:
  level: INFO
  baud_rate: 0

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

uart:
  id: my_uart
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

obis_d0:
  id: my_sm
  uart_id: my_uart
```

Using the minimal regexp option leads to same behavior btw.

Thanks!
